/**
 * @typedef {object} JobOffer
 * @property {string} identifier
 * @property {string} title
 * @property {string} jobType
 * @property {string} areaOfInterest
 * @property {string} publishedAt
 * @property {string} deadline
 * @property {string} startDate
 * @property {string} weeklyHours
 * @property {string} organization
 * @property {string} description
 * @property {string[]} requirements
 */

/** @type {JobOffer[]} */
export const MOCK_JOB_OFFERS = [
    {
        identifier: 'a1b2c3d4-0001-4000-8000-000000000001',
        title: 'Universitätsassistent*in im Bereich Elektrotechnik (m/w/d)',
        jobType: 'Universitätsstelle',
        areaOfInterest: 'Elektronik',
        publishedAt: '2026-01-15',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '40 h / Woche',
        organization: 'Institut für Elektrotechnik',
        description: 'Mitarbeit in Forschung und Lehre im Bereich Elektrotechnik.',
        requirements: [
            'Studium der Elektrotechnik oder eines verwandten Fachbereichs',
            'Grundkenntnisse in analoger und digitaler Schaltungstechnik',
        ],
    },
    {
        identifier: 'a1b2c3d4-0002-4000-8000-000000000002',
        title: 'Werkstudent*in (m/w/d) als Projektunterstützung 6h pro Woche',
        jobType: 'Werkstudentenstelle',
        areaOfInterest: 'Architektur & Bauwesen',
        publishedAt: '2026-02-01',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '6 h / Woche',
        organization: 'Institut für Bautechnik',
        description: 'Unterstützung laufender Projekte im Bereich Bauwesen.',
        requirements: [
            'Studium der Architektur, des Bauingenieurwesens oder ähnlichem',
            'Teamfähigkeit und Eigeninitiative',
        ],
    },
    {
        identifier: 'a1b2c3d4-0003-4000-8000-000000000003',
        title: 'Assistant Marketing Research (m/w/d) 20h',
        jobType: 'Teilzeitstelle',
        areaOfInterest: 'Kommunikation & Marketing',
        publishedAt: '2026-02-10',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '20 h / Woche',
        organization: 'Marketing Abteilung',
        description: 'Durchführung von Marktforschungsanalysen und Aufbereitung von Daten.',
        requirements: [
            'Studium der Wirtschaftswissenschaften, Marketing oder ähnlichem',
            'Erfahrung mit Datenanalyse-Tools',
        ],
    },
    {
        identifier: 'a1b2c3d4-0004-4000-8000-000000000004',
        title: 'Studentische Mitarbeiter*in: Planung Hochbau',
        jobType: 'Werkstudentenstelle',
        areaOfInterest: 'Architektur & Bauwesen',
        publishedAt: '2026-02-15',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '10 h / Woche',
        organization: 'Institut für Hochbau',
        description: 'Unterstützung bei Planungsaufgaben im Hochbau.',
        requirements: [
            'Studium der Architektur oder des Bauingenieurwesens',
            'CAD-Kenntnisse von Vorteil',
        ],
    },
    {
        identifier: 'a1b2c3d4-0005-4000-8000-000000000005',
        title: 'Student Support "Informationstechnologie" (m/w/d)',
        jobType: 'Werkstudentenstelle',
        areaOfInterest: 'Informatik',
        publishedAt: '2026-03-15',
        deadline: '2026-06-30',
        startDate: 'ab sofort',
        weeklyHours: '15 h / Woche',
        organization: 'Institut für Informatik',
        description:
            'Du suchst einen flexiblen Studentenjob, der nicht nur Deine Fähigkeiten stärkt, sondern Dich auch persönlich weiterbringt? Wir bieten Dir ein inspirierendes Arbeitsumfeld, das Offenheit, Vielfalt und Teamgeist lebt. Von Anfang an wirst Du aktiv in spannende Projekte eingebunden, sammelst wertvolle Praxiserfahrungen und trägst mit Deinem Engagement zur Umsetzung nachhaltiger Initiativen bei.',
        requirements: [
            'Du befindest dich gerade in einem relevanten Studienfach wie Wirtschaftsinformatik, Betriebswirtschaftslehre, Informatik oder einem ähnlichen Bereich',
            'Du hast Interesse am Bereich IT und insbes. an IT-Governance im Bankwesen. Du siehst dich als Zahlenjongleur, bringst eine analytische Denkweise mit und verstehst komplexe Zusammenhänge',
            'Du hast Engagement, gute Kommunikationsfähigkeiten und genießt Teamarbeit in einem agilen Setup',
            'Du bist sicher im Umgang mit MS Office, insbesondere Excel und PowerPoint. Erfahrung mit Jira oder Confluence',
        ],
    },
    {
        identifier: 'a1b2c3d4-0006-4000-8000-000000000006',
        title: 'Praktikant*in / Werkstudent*in im Bereich Reporting',
        jobType: 'Praktikum',
        areaOfInterest: 'Fahrzeugsicherheit',
        publishedAt: '2026-02-20',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '20 h / Woche',
        organization: 'Fahrzeugsicherheit Institut',
        description: 'Erstellung von Reports und Analysen im Bereich Fahrzeugsicherheit.',
        requirements: [
            'Studium der Fahrzeugtechnik oder ähnlichem',
            'Kenntnisse in Reporting-Tools und Datenvisualisierung',
        ],
    },
    {
        identifier: 'a1b2c3d4-0007-4000-8000-000000000007',
        title: 'Werkstudent*in R&D - Technical Design Tool (m/w/d)',
        jobType: 'Werkstudentenstelle',
        areaOfInterest: 'Architektur & Bauwesen',
        publishedAt: '2026-03-01',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '12 h / Woche',
        organization: 'R&D Abteilung',
        description: 'Mitarbeit bei der Entwicklung technischer Design-Tools.',
        requirements: [
            'Studium der Informatik, Architektur oder ähnlichem',
            'Kenntnisse in CAD oder 3D-Modellierung von Vorteil',
        ],
    },
    {
        identifier: 'a1b2c3d4-0008-4000-8000-000000000008',
        title: 'Marketing Mitarbeiter*in Schwerpunkt Digital Marketing & Social Media',
        jobType: 'Vollzeitstelle',
        areaOfInterest: 'Kommunikation & Marketing',
        publishedAt: '2026-03-05',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '38 h / Woche',
        organization: 'Kommunikationsabteilung',
        description: 'Betreuung und Weiterentwicklung der Social-Media-Kanäle.',
        requirements: [
            'Abgeschlossenes Studium im Bereich Marketing, Kommunikation oder ähnlichem',
            'Mehrjährige Erfahrung im Social-Media-Management',
        ],
    },
    {
        identifier: 'a1b2c3d4-0009-4000-8000-000000000009',
        title: 'Werkstudent:in im Bereich Produktdigitalisierung (teilzeit)',
        jobType: 'Werkstudentenstelle',
        areaOfInterest: 'Wärmetechnik',
        publishedAt: '2026-03-08',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '16 h / Woche',
        organization: 'Institut für Wärmetechnik',
        description: 'Unterstützung bei der Digitalisierung von Produktionsprozessen.',
        requirements: [
            'Studium der Wärmetechnik, Maschinenbau oder ähnlichem',
            'Grundkenntnisse in Digitalisierungstools und Datenbankmanagement',
        ],
    },
    {
        identifier: 'a1b2c3d4-0010-4000-8000-000000000010',
        title: 'Universitätsassistent*in im Bereich Elektrotechnik (m/w/d)',
        jobType: 'Universitätsstelle',
        areaOfInterest: 'Elektronik',
        publishedAt: '2026-01-20',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '40 h / Woche',
        organization: 'Institut für Halbleitertechnik',
        description: 'Forschung und Lehre im Bereich Halbleitertechnik.',
        requirements: [
            'Doktoratsstudium oder Abschluss der Elektrotechnik',
            'Forschungserfahrung im Bereich Halbleiter von Vorteil',
        ],
    },
    {
        identifier: 'a1b2c3d4-0011-4000-8000-000000000011',
        title: 'Werkstudent*in (m/w/d) als Projektunterstützung 6h pro Woche',
        jobType: 'Werkstudentenstelle',
        areaOfInterest: 'Architektur & Bauwesen',
        publishedAt: '2026-02-05',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '6 h / Woche',
        organization: 'Bauplanung GmbH',
        description: 'Projektunterstützung für laufende Bauprojekte.',
        requirements: [
            'Studium des Bauingenieurwesens oder ähnlichem',
            'Selbstständige Arbeitsweise und Organisationsgeschick',
        ],
    },
    {
        identifier: 'a1b2c3d4-0012-4000-8000-000000000012',
        title: 'Software-Entwickler*in (m/w/d) Backend',
        jobType: 'Vollzeitstelle',
        areaOfInterest: 'Informatik',
        publishedAt: '2026-03-10',
        deadline: '2030-03-31',
        startDate: 'ab sofort',
        weeklyHours: '38 h / Woche',
        organization: 'IT-Abteilung',
        description: 'Entwicklung und Wartung von Backend-Systemen.',
        requirements: [
            'Abgeschlossenes Studium der Informatik oder ähnlichem',
            'Kenntnisse in Java, Python oder Go',
            'Erfahrung mit RESTful APIs und Microservices',
        ],
    },
    {
        identifier: 'a1b2c3d4-0013-4000-8000-000000000013',
        title: 'Forschungsassistent*in Maschinenbau (m/w/d)',
        jobType: 'Universitätsstelle',
        areaOfInterest: 'Maschinenbau',
        publishedAt: '2026-01-25',
        deadline: '2030-02-28',
        startDate: 'ab sofort',
        weeklyHours: '40 h / Woche',
        organization: 'Institut für Maschinenbau',
        description: 'Mitarbeit in Forschungsprojekten im Bereich Maschinenbau.',
        requirements: [
            'Studium des Maschinenbaus oder ähnlichem',
            'Erfahrung mit FEM-Simulation von Vorteil',
        ],
    },
    {
        identifier: 'a1b2c3d4-0014-4000-8000-000000000014',
        title: 'Praktikant*in Datenanalyse (m/w/d)',
        jobType: 'Praktikum',
        areaOfInterest: 'Informatik',
        publishedAt: '2026-03-12',
        deadline: '2026-12-31',
        startDate: 'ab sofort',
        weeklyHours: '20 h / Woche',
        organization: 'Data Science Abteilung',
        description: 'Analyse und Visualisierung großer Datensätze.',
        requirements: [
            'Studium der Informatik, Statistik oder ähnlichem',
            'Kenntnisse in Python, R oder SQL',
        ],
    },
    {
        identifier: 'a1b2c3d4-0015-4000-8000-000000000015',
        title: 'Teamassistenz im Bereich Kommunikation (m/w/d)',
        jobType: 'Teilzeitstelle',
        areaOfInterest: 'Kommunikation & Marketing',
        publishedAt: '2026-02-25',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '20 h / Woche',
        organization: 'Kommunikationsabteilung',
        description: 'Unterstützung des Kommunikationsteams in administrativen Aufgaben.',
        requirements: [
            'Ausbildung oder Studium im Bereich Kommunikation oder Verwaltung',
            'Sehr gute MS-Office-Kenntnisse',
        ],
    },
    {
        identifier: 'a1b2c3d4-0016-4000-8000-000000000016',
        title: 'Werkstudent*in Energie- und Umwelttechnik (m/w/d)',
        jobType: 'Werkstudentenstelle',
        areaOfInterest: 'Wärmetechnik',
        publishedAt: '2026-03-02',
        deadline: '2030-06-30',
        startDate: 'ab sofort',
        weeklyHours: '15 h / Woche',
        organization: 'Institut für Energie- und Umwelttechnik',
        description: 'Mitarbeit in Projekten zur erneuerbaren Energie.',
        requirements: [
            'Studium der Energie- und Umwelttechnik oder ähnlichem',
            'Interesse an nachhaltigen Energiesystemen',
        ],
    },
    {
        identifier: 'a1b2c3d4-0017-4000-8000-000000000017',
        title: 'Junior Data Scientist (m/w/d)',
        jobType: 'Vollzeitstelle',
        areaOfInterest: 'Informatik',
        publishedAt: '2026-03-11',
        deadline: '2030-04-15',
        startDate: 'ab sofort',
        weeklyHours: '38 h / Woche',
        organization: 'AI Research Lab',
        description: 'Entwicklung von Machine-Learning-Modellen für industrielle Anwendungen.',
        requirements: [
            'Studium der Informatik, Mathematik oder ähnlichem',
            'Kenntnisse in Machine Learning und Deep Learning',
            'Erfahrung mit TensorFlow oder PyTorch von Vorteil',
        ],
    },
    {
        identifier: 'a1b2c3d4-0018-4000-8000-000000000018',
        title: 'Konstrukteur*in Fahrzeugtechnik (m/w/d)',
        jobType: 'Vollzeitstelle',
        areaOfInterest: 'Fahrzeugsicherheit',
        publishedAt: '2026-02-28',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '38 h / Woche',
        organization: 'Institut für Fahrzeugtechnik',
        description: 'Konstruktion und Auslegung von Fahrzeugkomponenten.',
        requirements: [
            'Studium der Fahrzeugtechnik, des Maschinenbaus oder ähnlichem',
            'Kenntnisse in CAD-Programmen (CATIA, SolidWorks)',
        ],
    },
    {
        identifier: 'a1b2c3d4-0019-4000-8000-000000000019',
        title: 'Lehrassistenz Grundlagen Elektrotechnik',
        jobType: 'Universitätsstelle',
        areaOfInterest: 'Elektronik',
        publishedAt: '2026-01-30',
        deadline: '2030-08-31',
        startDate: 'ab sofort',
        weeklyHours: '8 h / Woche',
        organization: 'Institut für Grundlagen der Elektrotechnik',
        description: 'Betreuung von Übungen und Tutorien in der Grundlagenausbildung.',
        requirements: [
            'Fortgeschrittenes Studium der Elektrotechnik',
            'Didaktische Fähigkeiten und Freude am Unterrichten',
        ],
    },
    {
        identifier: 'a1b2c3d4-0020-4000-8000-000000000020',
        title: 'Projektmanager*in Bauplanung (m/w/d)',
        jobType: 'Vollzeitstelle',
        areaOfInterest: 'Architektur & Bauwesen',
        publishedAt: '2026-03-06',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '38 h / Woche',
        organization: 'Bauplanung AG',
        description: 'Koordination und Steuerung von Bauprojekten.',
        requirements: [
            'Abgeschlossenes Studium des Bauingenieurwesens oder Projektmanagements',
            'Mehrjährige Erfahrung in der Bauplanung',
        ],
    },
    {
        identifier: 'a1b2c3d4-0021-4000-8000-000000000021',
        title: 'Praktikant*in im Bereich Wärmetechnik',
        jobType: 'Praktikum',
        areaOfInterest: 'Wärmetechnik',
        publishedAt: '2026-01-10',
        deadline: '2027-03-31',
        startDate: 'ab sofort',
        weeklyHours: '20 h / Woche',
        organization: 'Institut für Wärmetechnik',
        description: 'Praktische Mitarbeit in thermodynamischen Versuchsprojekten.',
        requirements: [
            'Studium der Wärmetechnik, des Maschinenbaus oder ähnlichem',
            'Interesse an experimenteller Forschung',
        ],
    },
    {
        identifier: 'a1b2c3d4-0022-4000-8000-000000000022',
        title: 'Content Creator & Social Media Manager*in (m/w/d)',
        jobType: 'Teilzeitstelle',
        areaOfInterest: 'Kommunikation & Marketing',
        publishedAt: '2026-03-09',
        deadline: '2030-01-01',
        startDate: 'ab sofort',
        weeklyHours: '20 h / Woche',
        organization: 'Marketingabteilung',
        description: 'Erstellung von Content für verschiedene Social-Media-Plattformen.',
        requirements: [
            'Studium der Kommunikationswissenschaften, Mediendesign oder ähnlichem',
            'Kreativität und Erfahrung in der Content-Erstellung',
        ],
    },
];
